# fly.toml app configuration file generated for metrosites-corner-nail-prototype-quiet-rain-197 on 2025-10-24T12:38:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metrosites-corner-nail-prototype-quiet-rain-197'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
